version: '3.8'

services:
  bot:
    container_name: bot
    build: .
    command: sh -c "python -m bot"
    environment:

      - REDIS_HOST=redis
      - REDIS_PORT=6379
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped
#    volumes:
#      - .:/app

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data
      - ./init.sh:/usr/local/bin/init.sh
    command: [ "sh", "-c", "/usr/local/bin/init.sh & redis-server" ]
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ;b;f4522
      POSTGRES_DB: postgres

    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

